Use same error message as other `bake` projects

diff --git a/Bakefile b/Bakefile
--- a/Bakefile
+++ b/Bakefile
@@ -5,8 +5,7 @@ SRC="src"
 
 build() {
   if [ -e "$OUT" ]; then
-    echo >&2 "Error: target already exists."
-    echo >&2 "Run 'clean' first."
+    echo >&2 "Error: Already built. Run \`clean\` first"
     echo >&2
     exit 1
   fi
